version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:14.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nplusone
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - "./volumes/db/postgresql/data:/var/lib/postgresql/data"
    restart: unless-stopped
    networks:
      - ${GLOBAL_NETWORK:-kafka}
