server:
  port: 3231

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 25
  jpa:
    open-in-view: false
#    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL9Dialect
#        generate_statistics: true
#        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:init-schema.sql
      data-locations: classpath:init-data.sql
      platform: postgres
